name: Build Main

on:
  push:
    branches: [ master ]

env:
  IMAGE_NAME: capabilities-tool

jobs:
  build-main:
    name: Build and push main snapshot images
    strategy:
      matrix:
        architecture: [amd64]
        platform: [linux]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch latest release version
        uses: reloc8/action-latest-release-version@1.0.0
        id: fetch-latest-release
      - name: Set Env Tags
        run: echo RELEASE_TAG=v0.0.0-test >> $GITHUB_ENV
      - name: set short sha
        run: echo SHA_SHORT=$(git rev-parse --short HEAD) >> $GITHUB_ENV
      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: quay.io/opdev/capabilities-tool
          tags: ${{ env.RELEASE_TAG }}
          archs: ${{ matrix.architecture }}
          build-args: |
            quay_expiration=1w
            release_tag=${{ env.RELEASE_TAG }}
            ARCH=${{ matrix.architecture }}
          dockerfiles: |
            ./Dockerfile
      - name: Login to registry
        id: registry-login
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: quay.io/opdev
      - name: Push Image
        id: push-image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.RELEASE_TAG }}
          registry: quay.io/opdev
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-image.outputs.registry-paths }}"

    outputs:
      imageName: ${{ env.IMAGE_NAME }}
      imageVersion: ${{ env.RELEASE_TAG }}
